version: "3.8"

services:
  app:
    build:
      context: ./docker/php
    container_name: prestamo_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - prestamo

  nginx:
    image: nginx:latest
    container_name: prestamo_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - prestamo

  postgres:
    image: postgres:16.8
    container_name: prestamo_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: prestamo_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prestamo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prestamo

  adminer:
    image: adminer:latest
    container_name: prestamo_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - prestamo
  node:
    image: node:22-alpine
    container_name: prestamo_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - prestamo

  composer:
    build:
      context: ./docker/php
    container_name: prestamo_composer
    working_dir: /var/www
    volumes:
      - .:/var/www
    entrypoint: ["composer"]
    networks:
      - prestamo

networks:
  prestamo:
    driver: bridge

volumes:
  postgres_data:
